server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: USER-SERVICE
  datasource:
    username: root
    password: Iconnect@1
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/userdb
  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true
#    database-platform: org.hibernate.dialect.MYSQL5InnoDBDialect
