server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: FOOD_CATALOUGE-SERVICE
  datasource:
    username: root
    password: Iconnect@1
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fooditemdb
  jpa:
    hibernate:
      ddl-auto: update

